export {
  RENT_START_OR_END_IS_WEEKEND_MESSAGE,
  RENT_TIME_IS_INVALID_MESSAGE,
  RENT_SESSION_DIDNT_CREATE_MESSAGE,
  INSET_RENT_SESSION_REQUEST_FAILED_MESSAGE,
  SELECT_CAR_IS_AVAILABLE_REQUEST_FAILED_MESSAGE,
  SELECT_CAR_USAGE_REPORT_REQUEST_FAILED_MESSAGE,
} from './errorMessages';
export {
  WEEKEND,
  BREAK_RENT_TIME,
  BASE_COST,
  MAX_RENT_TIME,
  MIN_RENT_TIME,
  TARIF_PLAN,
  MILLISECONDS_IN_ONE_DAY,
} from './appConfig';
